SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Sale;
TRUNCATE TABLE Promotion;
TRUNCATE TABLE Holiday;

TRUNCATE TABLE ProductCategory;
TRUNCATE TABLE StoreProduct;
TRUNCATE TABLE Membership;

TRUNCATE TABLE Product;
TRUNCATE TABLE Store;

TRUNCATE TABLE MembershipType;
TRUNCATE TABLE Category;
TRUNCATE TABLE Manufacturer;
TRUNCATE TABLE City;
TRUNCATE TABLE Calendar;

SET FOREIGN_KEY_CHECKS = 1;