export default [
  { id: "p0", title: "Home", path: "/" },
  {
    id: "p1",
    title: "View/Add Holiday",
    path: "holidays",
    fields: { Date: "holiday_date", Holiday: "holiday_name" },
  },
  {
    id: "p2",
    title: "Update City Population",
    path: "city-population",
    fields: { City: "city", State: "state", Population: "population" },
  },
  {
    id: "p3",
    title: "Manufacturer's Product Report",
    path: "manufacturer-product-report",
    fields: {
      "Manufacturer ID": "manufacturer_id",
      "Manufacturer Name": "manufacturer_name",
      "Total Products Offered": "total_products_offered",
      "Avg Retail Price": "avg_retail_price",
      "Min Retail Price": "min_retail_price",
      "Max Retail Price": "max_retail_price",
      "Retail Price Range": "retail_price_range",
    },
    detail_fields: {
      l1: {
        "Manufacturer ID": "manufacturer_id",
        "Manufacturer Name": "manufacturer_name",
        "Maximum Discount": "maximum_discount",
      },
      l2: {
        "Product ID": "product_id",
        "Product Name": "product_name",
        "Category(s)": "category",
        "Retail Price": "retail_price",
      },
    },
  },
  {
    id: "p4",
    title: "Category Report",
    path: "category-report",
    fields: {
      "Category Name": "category_name",
      "Total Products": "total_products",
      "Total Manufacturers": "total_manufacturers",
      "Avg Retail Price": "avg_retail_price",
      "Total Revenue": "total_revenue",
    },
  },
  {
    id: "p5",
    title: "Actual vs. Predicted Revenue for Speaker Units",
    path: "speaker-revenue-comparison",
    fields: {
      "Product ID": "product_id",
      "Product Name": "product_name",
      "Retail Price": "retail_price",
      "Total Units Sold": "total_units_sold",
      "Total Units Sold At Discount": "total_units_sold_at_discount",
      "Total Units Sold At Retail": "total_units_sold_at_retail",
      "Actual Revenue": "actual_revenue",
      "Predicted Revenue": "predicted_revenue",
      "Predicted Revenue Diff": "predicted_revenue_diff",
    },
  },
  {
    id: "p6",
    title: "Store Revenue by Year by State",
    path: "store-revenue-by-year-by-state",
    fields: {
      "Store Number": "store_number",
      "Street Address": "street_address",
      "Zip Code": "zip_code",
      "City Name": "city",
      "Sales Year": "sales_year",
      "Total Revenue": "total_revenue",
      "Total Revenue At Retail": "total_revenue_at_retail",
      "Total Revenue At Discount": "total_revenue_at_discount",
    },
  },
  {
    id: "p7",
    title: "Air Conditioners on Groundhog Day",
    path: "groundhog-day-ac",
    fields: {
      "Sales Year": "sales_year",
      "Total AC Units Sold": "total_AC_units_sold",
      "Avg AC Units Sold Per Day": "avg_AC_units_sold_per_day",
      "Total Units Sold On Groundhog Day": "total_units_sold_on_groundhog_day",
    },
  },
  {
    id: "p8",
    title: "State with Highest Volume for each Category",
    path: "category-top-state",
    fields: {
      "Category Name": "category_name",
      "Highest Sold State": "highest_sold_state",
      "Total Units Sold": "total_units_sold",
    },
  },
  {
    id: "p9",
    title: "Revenue per Population",
    path: "revenue-per-population",
    fields: {
      "Sales Year": "sales_year",
      "Avg Revenue Small Cities": "avg_revenue_small_cities",
      "Avg Revenue Medium Cities": "avg_revenue_medium_cities",
      "Avg Revenue Large Cities": "avg_revenue_large_cities",
      "Avg Revenue Extra Large Cities": "avg_revenue_extra_large_cities",
    },
  },
  {
    id: "p10",
    title: "Membership Trend",
    path: "membership-trend",
    fields: {
      "Signup Year": "signup_year",
      "Total Memberships Sold": "total_memberships_sold",
    },
    detail_fields: {
      l1: {
        City: "city",
        State: "state",
        "Total Memberships Sold": "total_memberships_sold",
      },
      l2: {
        "Store Number": "store_number",
        "Street Address": "street_address",
        "Zip Code": "zip_code",
        City: "city",
        State: "state",
        "Total Memberships Sold": "total_memberships_sold",
      },
    },
  },
];
